[PURPLE-58] 이메일 인증 전송 API
perfume-pick/purple-server pull request #15
Opened 2024-04-17 09:34 UTC by JHyeonC

### Summary
- 이메일 인증 전송에 필요한 값은 userEmail, verifyNumber, expirationTime입니다.
- expirationTime은 내부적으로 정하거나, 조율이 필요할 것 같습니다.
- 이메일 인증 전송을 할 때 동기식으로 처리한다면 Latency가 길어져 infra의 mailsender를 비동기식으로 처리하였습니다.(평균 3s -> 300ms)
- 추후 이메일 인증번호 검증 API, DTO record로 관리 작업할 에정입니다.

2024-04-18 02:15 UTC, wonjunYou requested changes
고생하셨습니다! 전반적으로 컨벤션에 관한 피드백이 많았네요 ㅠ
처음에는 다소 번거롭게 느껴지실 수 있겠지만 금방 좋아질 것 같아요 ㅎㅎㅎ

수정하시고 나면 re-request review 부탁드립니다 :)

2024-04-18 02:15 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/bootstrap/common/exception/GlobalExceptionHandler.java
> +        if (errorCode.getStatus() == HttpStatus.INTERNAL_SERVER_ERROR.value()) {
p4)
```suggestion

    @ExceptionHandler(BusinessException.class)
    public ResponseEntity<?> handleBusinessException(BusinessException e) {
        ErrorCode errorCode = e.getErrorCode();
        if (errorCode.getStatus() == HttpStatus.INTERNAL_SERVER_ERROR.value()) {
```

2024-04-18 02:15 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/common/AsyncConfig.java
> +        threadPoolTaskExecutor.setMaxPoolSize(Runtime.getRuntime().availableProcessors() * 2);
p3) 개인적인 궁금함인데요, 혹시 maxPoolSize를 잡는 기준이 있나요?

2024-04-18 02:15 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/infrastructure/mail/adaptor/MailSenderAdaptor.java
> +    @Async
p4)
```suggestion
public class MailSenderAdaptor implements MailSender {

    private final JavaMailSender javaMailSender;
    
    @Override
    @Async
```

2024-04-18 02:15 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/infrastructure/redis/user/adapter/UserEmailVerificationRedisAdaptor.java
> +    com.pikachu.purple.application.user.port.out.UserEmailVerificationRepository {
p2) 요거 import가 조금 이상한 것 같아요!!

2024-04-18 02:15 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/infrastructure/redis/user/adapter/UserEmailVerificationRedisAdaptor.java
> +    public void save(String email, String verifiedNumber, Long expirationTime){
p4)
```suggestion
    public void save(
      String email, 
      String verifiedNumber, 
      Long expirationTime
    ) {
```

2024-04-18 02:15 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/infrastructure/redis/user/entity/UserEmailVerificationRedisHash.java
> +    @Id
p4) entity 필드는 줄바꿈 들어가는 게 좋을 것 같아요

2024-04-18 02:15 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/infrastructure/user/adaptor/UserJpaAdaptor.java
> +                throw BusinessException.EmailExistedException;});
p4) 여기도 줄바꿈 부탁드립니다!!

2024-04-18 02:15 UTC, wonjunYou commented on src/main/resources/application.yaml
> +    username: team.perpicks@gmail.com
p3) 이메일 주소도 환경변수로 관리되면 좋을 것 같아요!

2024-04-18 05:17 UTC, JHyeonC commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-mail'
제가 저번에 잘못 설명해드렸는데, 좀 더 자세히 찾아보니 spring-boot-starter를 이용해 의존성을 추가한다면 spring-boot-starter-parent에 정의되어 있는 의존성을 상속받기 때문에 따로 버전을 명시해줄 필요가 없다고 합니다.

추후에 프로젝트에서 사용하고 있는 의존성들과 버전이 맞지 않아 충돌할 경우 버전을 명시하는 방향으로 가는 것은 어떨까요?

2024-04-18 06:08 UTC, JHyeonC commented on src/main/java/com/pikachu/purple/bootstrap/auth/dto/request/EmailVerificationRequest.java
> +@NoArgsConstructor(force = true)
NoArgsConstructor는 기본 생성자 생성 시 final 변수를 초기화하지 않습니다! final 변수를 초기화시키지 않고 기본 생성자를 생성 할 시 컴파일 에러가 발생하기 합니다. 이러한 이유 때문에 force=true를 사용해 final 필드를 기본값으로 강제 초기화 합니다~

2024-04-18 06:42 UTC, JHyeonC commented on src/main/java/com/pikachu/purple/common/AsyncConfig.java
> +        threadPoolTaskExecutor.setMaxPoolSize(Runtime.getRuntime().availableProcessors() * 2);
CorepoolSize와 MaxPoolSize를 잡는 기준은 프로젝트 환경마다 다를 것 같습니다. 서비스 개발이 완료되고, 성능 테스트를 할 때 저희 프로젝트에 맞는 설정 값을 찾아야합니다!

2024-04-19 05:09 UTC, wonjunYou commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-mail'
좋습니다!

2024-04-19 05:13 UTC, wonjunYou approved these changes
너무 고생하셨습니다! 코드가 훨씬 좋아졌어요 👏👏

자잘한 수정사항들만 반영하고 머지하시면 될 것 같아요 ㅎ

2024-04-19 05:13 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/application/user/service/application/SendEmailVerificationService.java
> +    private static final Long MAX_EXPIRATION_TIME = 600L;
p5) 사소한 피드백인데, TIME이 시간(초) 기준인가요? 그렇다면 EXPIRATION_SECONDS라고 명시되면 좋을 것 같아요!

2024-04-19 05:13 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/common/AsyncConfig.java
> +        threadPoolTaskExecutor.setMaxPoolSize(Runtime.getRuntime().availableProcessors() * 2);
아하 확인했습니다!

2024-04-19 05:13 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/domain/user/User.java
> +    ){
p4) 
```suggestion
    ) {
```

2024-04-19 06:40 UTC, JHyeonC commented on src/main/java/com/pikachu/purple/application/user/service/application/SendEmailVerificationService.java
> +    private static final Long MAX_EXPIRATION_TIME = 600L;
초 기준이 맞습니다! 그렇게 변경하겠습니다 ㅎㅎ

2024-04-19 06:45 UTC, JHyeonC commented
머지하겠습니다!

2024-04-19 06:45 UTC, merged