[Purple-12] 회원가입 UseCase
perfume-pick/purple-server pull request #30
Opened 2024-05-07 07:05 UTC by JHyeonC

### 진행상황
- User Attirute는 id, email, nickname, registerAt, socialLoginProvider로 구성하였습니다.
- entity pk는 time-based, yyyymmddssSSSS로 18자리로 구성됩니다.

2024-05-08 06:59 UTC, wonjunYou requested changes
고생하셨습니다!!

2024-05-08 06:59 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/application/user/port/in/SignUpUseCase.java
> +    }
p4) 
```suggestion
    ) {
    }
```

2024-05-08 06:59 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/application/user/port/out/UserRepository.java
> +    int countTotalUsers();
p4)
```suggestion
    int countAll()
```
 같은 네이밍이 어떨까요..?

2024-05-08 06:59 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/application/user/service/application/SignUpService.java
> +public class SignUpService implements SignUpUseCase {
p3) 파일명에 대한 일관성이 깨지는 것 같습니다! 도메인명 + 행위명 의 조합으로 해오고 있었는데, 혹시 변경이 필요할까요?
```suggestion
public class UserSignUpService implements UserSignUpUseCase {
```

2024-05-08 06:59 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/application/user/service/application/SignUpService.java
> +            User createUser = User.create(
p4) 동사가 붙는 건 다소 자연스럽지 못한 것 같아요
```suggestion
            User createdUser = User.create(
```

2024-05-08 06:59 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/application/user/service/application/SignUpService.java
> +                NicknameCreator.create(userDomainService.countTotalUsers()).getNickName(),
p3) Nickname이라는 VO에서 내부적으로 생성하고 처리하는 건 어떨까요??

2024-05-08 06:59 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/application/user/service/application/SignUpService.java
> +                NicknameCreator.create(userDomainService.countTotalUsers()).getNickName(),
p3) NicknameCreater.create를 통해 생성한 결과물이 닉네임이 아니라, getNickname으로 가져와야 하는 것이 조금 부자연스러운 것 같습니다!

2024-05-08 06:59 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/application/user/service/domain/UserDomainService.java
> +    );
p4)
```suggestion
    void create(User createUser);
```

2024-05-08 06:59 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/application/user/service/domain/impl/UserDomainServiceImpl.java
> +            .build();
p3) 여기도 createUser라는 변수명 변경 필요할 것 같아요!

2024-05-08 06:59 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/application/user/service/domain/impl/UserDomainServiceImpl.java
> +            .registerAt(createUser.getRegisterAt())
p4) 
```suggestion
            .registeredAt(createUser.getRegisterAt())
```

2024-05-08 06:59 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/application/user/vo/NicknameCreator.java
> +package com.pikachu.purple.application.user.vo;
p3) 해당 유틸성 클래스가 vo랑은 다소 거리가 있는 것 같습니다!

2024-05-08 06:59 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/application/user/vo/NicknameCreator.java
> +}
p3) 추가적으로 아까 언급한 사항이긴 한데, NicknameCreator에서 create의 결과가 NicknameCreator를 그대로 반환하는 건 어색한 것 같습니다 🙂
```suggestion
import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public class NicknameCreator {

    private static final String NICKNAME_FORMAT = "퍼픽%03d";
    private final String nickname;

    public static NicknameCreator create(int userTotalCount){
        String createdNickname = String.format(NICKNAME_FORMAT, countTotalUsers+1);
        return new NicknameCreator(createdNickname);
    }

}
```

2024-05-08 06:59 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/domain/user/User.java
> +            null,
p2) id까지 생성자로 잡고 null을 넘기는 이유가 있나요??

2024-05-08 06:59 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/domain/user/User.java
>  }
p4)
```suggestion
    }

}
```

2024-05-08 06:59 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/infrastructure/persistence/user/adaptor/UserJpaAdaptor.java
> +                socialLoginProvider
p4) 컨벤션 확인해주셔용 ㅎ

2024-05-08 11:33 UTC, JHyeonC commented on src/main/java/com/pikachu/purple/application/user/service/application/SignUpService.java
> +public class SignUpService implements SignUpUseCase {
죄송합니다! 기존 네이밍 컨벤션으로 수정하겠습니다

2024-05-08 12:40 UTC, JHyeonC commented on src/main/java/com/pikachu/purple/application/user/vo/NicknameCreator.java
> +}
해결 완료!

2024-05-10 03:24 UTC, wonjunYou approved these changes
수정사항 검토하시고 merge 하면 될 것 같습니다!

2024-05-10 03:24 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/application/user/port/in/UserSignUpUseCase.java
> +
p4) 본문이 없는 경우 LF는 지워주세요!

2024-05-10 03:24 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/application/user/service/application/UserUserSignUpService.java
> +public class UserUserSignUpService implements UserSignUpUseCase {
p3) 클래스명 체크 부탁드립니다!

2024-05-10 03:24 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/application/user/vo/Nickname.java
> +        return String.format("퍼픽%03d", countTotalUsers+1);
p3) 요거 매직넘버로 처리하면 좋을 것 같아요!

2024-05-10 03:24 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/bootstrap/common/exception/BusinessException.java
> +    public static final BusinessException NicknameAlreadyException = new BusinessException(
p3) 익셉션 명을 `NicknameAlreadyExistException`로 하는 것이 어떨까요?

2024-05-10 03:24 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/domain/user/User.java
> +        this.registerAt = registerAt;
p4) 요거 registeredAt으로 쓰는 게 어떨까요?

2024-05-10 03:24 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/infrastructure/persistence/user/adaptor/UserJpaAdaptor.java
> +                throw NicknameAlreadyException;});
p4) 괄호도 들여쓰기 해서 맞춰주시면 좋을 것 같습니다~~

2024-05-10 06:02 UTC, merged