[PURPLE-83] 선호기반추천향수리스트조회 API
perfume-pick/purple-server pull request #40
Opened 2024-06-03 04:40 UTC by JHyeonC

### 진행상황
- 온보딩에서 저장한 별점을 이용하여, 추천 알고리즘을 통해 top3 노트를 추출하였습니다.
- 추출한 노트를 UserPrefereneNote Entity에 저장하였습니다.
- 저장한 노트를 기반으로 추천 향수들을 조회합니다. (현재는 노트를 가장 많이 포함된 향수들을 DESC로 정렬하여 최대 30개까지 조회합니다)
- 아직 comment 부분은 미구현으로 추후에 리팩토링 할 예정입니다.

2024-06-04 05:39 UTC, wonjunYou requested changes
리뷰 확인 부탁드립니다! 고생하셨어요 ㅎ

2024-06-04 05:39 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/application/perfume/service/application/PerfumeGetByUserPreferenceNoteApplicationService.java
> +        UserPreferenceNoteGetUseCase.Result result = userPreferenceNoteGetUseCase.invoke();
p3) result보다 명확한 변수명이 되었으면 좋겠습니다!!

2024-06-04 05:39 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/application/perfume/util/RecommendNotesProvider.java
> +    }
p3) put으로 넣기보다 생성과 동시에 초기화하면서 넣어도 좋지 않을까 싶습니다!

2024-06-04 05:39 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/application/rating/port/in/RatingGetByUserIdUseCase.java
> +    record Result(List<Rating> ratingList){
p4)
```suggestion
    record Result(List<Rating> ratingList) {
```

2024-06-04 05:39 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/application/rating/service/application/RatingSaveApplicationService.java
>      private static final int ZERO = 0;
p3) 엇 이걸 이제 확인했네요.. 숫자 값 자체를 영어로 매직넘버 처리하는 것은 의미가 없는 것 같아요.

2024-06-04 05:39 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/application/rating/service/domain/RatingDomainService.java
> +    List<Rating> getByUserId(Long userId);
p4) getAllByUserId가 되어야 할 것 같아요!

2024-06-04 05:39 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/application/userPreferenceNote/service/application/UserPreferenceNoteSaveApplicationService.java
> +        List<Note> topThreeNoteList = recommendNotesProvider.getTopThreeNotes(
p3) ~List라는 네이밍보다 s로 끝나는 네이밍이 조금 더 자연스러운 것 같은데, 이건 어떻게 생각하시나요 ㅎㅎ

2024-06-04 05:39 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/application/userPreferenceNote/service/application/UserPreferenceNoteSaveApplicationService.java
> +        List<Long> userPreferenceNoteIdList = IntStream.range(0, topThreeNoteList.size())
p3) topThreeNoteList.size() 는 항상 3으로 고정인 것 같은데, 상수로 처리하는 게 어떨까요?

2024-06-04 05:39 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/bootstrap/perfume/api/PerfumeApi.java
> +    @GetMapping("/preference-based/recommend")
p2) api path가 향수 리스트 조회이니 `perfumes/`으로 시작해야 할 것 같습니다! 기타 부수적인 수식어가 많은데 조금 더 간결하게 표현되어도 좋을 것 같아요

2024-06-04 05:39 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/domain/perfume/PerfumeNote.java
> +    }
p4) toString() overriding 하신 이유가 있을까요??

2024-06-04 05:39 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/infrastructure/persistence/note/entity/NoteJpaEntity.java
> +    private String noteName;
p4) 이거 그냥 name이라고 해도 좋을 것 같습니다 !

2024-06-04 05:39 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/adaptor/PerfumeJpaAdaptor.java
> +    private final static int THIRTY = 30;
p2) 해당 매직넘버 네이밍도 수정이 필요할 것 같아요

1. 0은 매직넘버 처리가 불필요하다고 알고 있습니다!
2. 30이 의미하는 바를 드러내주시면 좋을 것 같습니다!

2024-06-04 05:39 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/entity/PerfumeNoteJpaEntity.java
> +    @Column(name = "noteName")
p3) 
```suggestion
    @Column(name = "note_name")
```

2024-06-04 05:39 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/infrastructure/persistence/rating/repository/RatingJpaRepository.java
> +    List<RatingJpaEntity> findByUserId(Long userId);
p4) 이거 쿼리 안 짜도 같지 않나요..??

2024-06-06 06:14 UTC, JHyeonC commented on src/main/java/com/pikachu/purple/application/perfume/port/out/PerfumeNoteRepository.java
> +    List<PerfumeNote> getByPerfumeIdList(List<Long> perfumeList);
좋습니다!

2024-06-06 06:17 UTC, JHyeonC commented on src/main/java/com/pikachu/purple/domain/perfume/PerfumeNote.java
> +    }
앗 죄송합니다 요거 테스트한다고 집어넣었는데 삭제를 안했네요ㅠㅠ

2024-06-06 06:24 UTC, JHyeonC commented on src/main/java/com/pikachu/purple/application/rating/service/application/RatingSaveApplicationService.java
>      private static final int ZERO = 0;
요기서는 매직넘버를 사용하지 않겠습니다!

2024-06-06 06:29 UTC, JHyeonC commented on src/main/java/com/pikachu/purple/application/userPreferenceNote/service/application/UserPreferenceNoteSaveApplicationService.java
> +        List<Note> topThreeNoteList = recommendNotesProvider.getTopThreeNotes(
저는 평소에 list라고 네이밍을 했었는데, s로 사용하는 것도 좋아보이네요. 그러면 s로 통일시켜볼까요?

2024-06-06 06:29 UTC, JHyeonC commented on src/main/java/com/pikachu/purple/application/userPreferenceNote/service/application/UserPreferenceNoteSaveApplicationService.java
> +        List<Long> userPreferenceNoteIdList = IntStream.range(0, topThreeNoteList.size())
넵 상수처리가 좋아보이네요!! 수정하겠습니다.

2024-06-13 10:09 UTC, wonjunYou approved these changes
아래 comment만 챙겨주시고 merge 하시면 될 것 같아요~~ 고생하셨습니닷

2024-06-13 10:09 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/application/perfume/port/out/PerfumeNoteRepository.java
> +    List<PerfumeNote> getAllByPerfumeIds(List<Long> perfumeList);
p5) 파라미터의 ~~~리스트 요거는 아직 반영 안 된거죠?? 나중에 일괄적으로 챙겨주세용 ㅎ

2024-06-13 10:09 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/application/perfume/util/RecommendNotesProvider.java
> +    }};
p2) 이렇게 가는 건 어떨까요??
```suggestion
    private static final Map<Double, Double> weightMap = Map.of(
        5.0, 1.0,
        4.5, 0.9,
        4.0, 0.8,
        3.5, 0.7,
        3.0, 0.0,
        2.5, 0.0,
        2.0, -0.7,
        1.5, -0.8,
        1.0, -0.9,
        0.5, -1.0
    );
```

2024-06-13 10:09 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/bootstrap/perfume/api/PerfumeApi.java
> +    @GetMapping("/prefer-note")
p3) /preference 가 명사형이고, 직관적인 느낌에서 더 나을 것 같은데 어떨까요 ㅎㅎ

2024-06-13 11:05 UTC, JHyeonC commented on src/main/java/com/pikachu/purple/application/perfume/util/RecommendNotesProvider.java
> +    }};
좋습니다!

2024-06-13 11:05 UTC, JHyeonC commented on src/main/java/com/pikachu/purple/application/perfume/port/out/PerfumeNoteRepository.java
> +    List<PerfumeNote> getAllByPerfumeIds(List<Long> perfumeList);
넵 이거는 일괄적으로 따로 refactoring pr로 빼겠습니다!

2024-06-13 11:08 UTC, JHyeonC commented on src/main/java/com/pikachu/purple/bootstrap/perfume/api/PerfumeApi.java
> +    @GetMapping("/prefer-note")
preference-note로 수정하겠습니다!

2024-06-13 11:08 UTC, merged