[PURPLE-129] 향수 상세정보 호출 API 구현Feat/purple 128
perfume-pick/purple-server pull request #78
Opened 2024-08-28 19:47 UTC by dj-1087

## 진행상황
- 향수 상세정보 호출 API 구현 

### API 명세
- 응답 정보
![스크린샷 2024-08-29 오전 4 43 12](https://github.com/user-attachments/assets/afc24bf5-7f02-4be7-9526-0847efe34b79)

<details>
<summary>결과 샘플</summary>
<div markdown="2">

```json
{
  "timeStamp": "2024-08-29T04:35:23.795567",
  "responseData": {
    "perfumes": {
      "perfumeId": 2024082904333332700,
      "perfumeName": "Gucci",
      "brandName": "Gucci",
      "imageUrl": "https://fimgs.net/mdimg/perfume/m.75190.jpg",
      "mainAccords": [
        {
          "noteName": "amber",
          "accordValue": 47
        },
        {
          "noteName": "citrus",
          "accordValue": 100
        },
        {
          "noteName": "floral",
          "accordValue": 85
        },
        {
          "noteName": "fresh spicy",
          "accordValue": 53
        },
        {
          "noteName": "warm spicy",
          "accordValue": 53
        }
      ],
      "perfumeNotes": [
        {
          "noteName": "Italian Mandarin",
          "perfumeNoteType": "TOP"
        },
        {
          "noteName": "Bergamot",
          "perfumeNoteType": "TOP"
        },
        {
          "noteName": "Black Pepper",
          "perfumeNoteType": "TOP"
        },
        {
          "noteName": "Jasmine",
          "perfumeNoteType": "MIDDLE"
        },
        {
          "noteName": "Jasmine Sambac",
          "perfumeNoteType": "MIDDLE"
        },
        {
          "noteName": "Magnolia",
          "perfumeNoteType": "MIDDLE"
        },
        {
          "noteName": "Damask Rose",
          "perfumeNoteType": "MIDDLE"
        },
        {
          "noteName": "Benzoin",
          "perfumeNoteType": "BASE"
        },
        {
          "noteName": "Australian Sandalwood",
          "perfumeNoteType": "BASE"
        },
        {
          "noteName": "Patchouli",
          "perfumeNoteType": "BASE"
        }
      ]
    }
  }
}

```

</div>
</details>

## 추후 PR
- Redis를 이용한 최근 방문 상품 기록 (임시: userSaveVisitedHistoryUseCase)
- 프라그란티카 평가 정보 조회 API 구현

2024-08-29 12:53 UTC, JHyeonC commented on src/main/java/com/pikachu/purple/application/perfume/service/application/PerfumeDetailGetByPerfumeIdApplicationService.java
> +    private final int MAX_SIZE = 5;
p3) 변하지 않는 값이라면 매직 넘버로 표현하는건 어떨까요?
```suggestion
    private static final int MAX_SIZE = 5;
```

2024-08-29 12:54 UTC, JHyeonC commented on src/main/java/com/pikachu/purple/application/mainAccord/port/out/MainAccordRepository.java
> +    List<MainAccord> findAllByPerfumeId(Long perfumeId, int maxSize);
p4)
```suggestion
    List<MainAccord> findAllByPerfumeId(
    Long perfumeId, 
    int maxSize
    );
```

2024-08-29 12:55 UTC, JHyeonC commented on src/main/java/com/pikachu/purple/application/mainAccord/service/domain/impl/MainAccordDomainServiceImpl.java
> +        return mainAccordRepository.findAllByPerfumeId(perfumeId, maxSize);
p4)
```suggestion
    public List<MainAccord> findAllByPerfumeId(
        Long perfumeId, 
        int maxSize
     ) {
        return mainAccordRepository.findAllByPerfumeId(
            perfumeId, 
            maxSize
        );
```

2024-08-29 12:56 UTC, JHyeonC commented on src/main/java/com/pikachu/purple/application/perfume/port/in/PerfumeDetailGetByPerfumeIdUseCase.java
> +    record Command(Long perfumeId){}
p4)
```suggestion
    record Command(Long perfumeId) {
    
    }
```

2024-08-29 12:57 UTC, JHyeonC commented on src/main/java/com/pikachu/purple/application/perfume/service/application/PerfumeDetailGetByPerfumeIdApplicationService.java
> +        List<MainAccord> mainAccords = mainAccordDomainService.findAllByPerfumeId(perfume.getPerfumeId(), MAX_SIZE);
p4) 여기도 컨벤션 맞춰주세요!

2024-08-30 04:36 UTC, JHyeonC commented on src/main/java/com/pikachu/purple/application/perfume/service/application/PerfumeDetailGetByPerfumeIdApplicationService.java
> +        List<MainAccord> mainAccords = mainAccordDomainService.findAllByPerfumeId(perfume.getPerfumeId(), MAX_SIZE);
파라미터가 하나이면
Purfume perfume = perfumeDomainService.findByPerfumeId(command.PerfumeId());
라고 하셔도 됩니다!

2024-08-30 05:58 UTC, wonjunYou requested changes
고생하셨습니다~

2024-08-30 05:58 UTC, wonjunYou commented on data/crawling_data/Acqua di Parma.json
p3) 정적 파일은 디렉토리 위치를 src/main/resources 쪽에서 관리하는게 나을 것 같아요

2024-08-30 05:58 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/bootstrap/perfume/api/PerfumeApi.java
> +        @RequestParam List<String> request);
p4) 이거 줄바꿈 들어간 이유가 있나요??

2024-08-30 05:58 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/bootstrap/perfume/dto/response/GetPerfumeDetailResponse.java
> +}
p3) EOF

2024-08-30 05:58 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/domain/perfume/PerfumeDetail.java
> +    // perfume
p4) 불필요한 주석은 지워도 될 것 같아요~

2024-08-30 05:58 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/domain/perfume/PerfumeNote.java
> +    @JsonIgnore
p3) DDD에서 순수 도메인은 어떠한 dependency에도 의존적일 수 없어요!

2024-08-30 05:58 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/domain/perfume/PerfumeDetail.java
> +package com.pikachu.purple.domain.perfume;
p3) 해당 객체는 순수한 도메인 객체라기보다는 응답값을 위한 객체에 가까운 것 같아요

2024-08-30 05:58 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/infrastructure/persistence/mainAccord/repository/MainAccordJpaRepository.java
> +}
p3) EOF

2024-08-30 05:58 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/adaptor/PerfumeNoteJpaEntityAdaptor.java
> +            .collect(Collectors.toList());
p3)
```suggestion
            .toList();
```

2024-08-30 06:47 UTC, dj-1087 commented on src/main/java/com/pikachu/purple/bootstrap/perfume/api/PerfumeApi.java
> +        @RequestParam List<String> request);
최대 줄 너비를 초과하여 구글 스타일 자동정렬 시 줄바꿈 들어간 것 같습니다.

```java
SuccessResponse<GetPerfumeByBrandsResponse> getPerfumeByBrands(
        @RequestParam List<String> request
);
```
이런식으로 바꿀까요?

2024-08-30 06:59 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/bootstrap/perfume/api/PerfumeApi.java
> +        @RequestParam List<String> request);
음.. 자동으로 바뀐거면 그대로 냅둬도 될 것 같아요 ㅎ
오히려 파라미터 하나에 불필요한 줄바꿈은 없애는 게 낫다고 봐서..

2024-09-02 15:31 UTC, JHyeonC commented on src/main/java/com/pikachu/purple/application/perfume/common/dto/PerfumeAccordDto.java
> +public record PerfumeAccordDto(String noteName, int accordValue) {
p4)
```suggestion
public record PerfumeAccordDto(
      String noteName,
      int accordValue
      ) {
```

2024-09-02 15:33 UTC, JHyeonC commented on src/main/java/com/pikachu/purple/application/perfume/service/application/PerfumeDetailGetByPerfumeIdApplicationService.java
> +    private final PerfumeAccordDomainService perfumeAccordDomainService;
p4) 이 부분은 원준님과 상의해보셨나요??

2024-09-02 15:36 UTC, JHyeonC commented on src/main/java/com/pikachu/purple/bootstrap/perfume/api/PerfumeApi.java
> +    @GetMapping("/{perfume-id}/detail")
p3) 향수 상세 정보 조회를 할 때 URI에서 정확히 어떤 부분이지 구분할 수 있으면 좋을것 같아요!

2024-09-02 15:37 UTC, JHyeonC reviewed
고생하셨습니다! 코멘트 확인 부탁드릴게요 ㅎㅎ

2024-09-02 16:38 UTC, dj-1087 commented on src/main/java/com/pikachu/purple/application/perfume/service/application/PerfumeDetailGetByPerfumeIdApplicationService.java
> +    private final PerfumeAccordDomainService perfumeAccordDomainService;
@wonjunYou 이거 어떻게 생각하시나요?
ApplicationService 내에 여러 Domain에 대한 서비스 로직(CURD)이 필요한 경우, 
종현님께서 각 Domain 서비스 로직에 대한 UseCase 인터페이스 및 ApplicationService 구현체를 구현 후 해당 UseCase를 주입하는게 낫다고 의견을 주셨습니다.
저의 생각으로는 Controller에서 호출하지도 않고 Service 레이어 내에서만 사용하는데, 단순 Domain 로직에 대해 UseCase 및 ApplicationService를 구현하는 것은 쓸데없는 코드만 늘어나는 것 같습니다.

![image](https://github.com/user-attachments/assets/380a1e5e-c6aa-4241-8d5c-e102fb2cb16b)

2024-09-03 04:18 UTC, wonjunYou commented on src/main/java/com/pikachu/purple/application/perfume/service/application/PerfumeDetailGetByPerfumeIdApplicationService.java
> +    private final PerfumeAccordDomainService perfumeAccordDomainService;
여러 도메인이라는게 어떤 도메인이냐에 따라 다를 것 같은데요, 만약 같은 패키지 내의 하위 도메인의 경우에는 application service에서 바로 참조할 수 있고, 다른 패키지에 존재하는 경우에는 inbound port를 통해 참조해야 서로 간의 의존성을 최소화할 수 있을 것 같아요

2024-09-03 04:31 UTC, dj-1087 commented on src/main/java/com/pikachu/purple/application/perfume/service/application/PerfumeDetailGetByPerfumeIdApplicationService.java
> +    private final PerfumeAccordDomainService perfumeAccordDomainService;
넵 그럼 일단 현재 사용하고있는 DomainService 들은 모두 같은 패키지 내의 하위 인터페이스이므로 수정을 따로 하지 않겠습니다, 
차후 다른 패키지의 DomainService를 사용하게 될 경우 유의하겠습니다!

2024-09-03 06:02 UTC, JHyeonC commented on src/main/java/com/pikachu/purple/infrastructure/persistence/perfume/repository/PerfumeAccordJpaRepository.java
> +    List<PerfumeAccordJpaEntity> findAllByPerfumeId(Long perfumeId, Limit limit);
p4)

2024-09-03 06:03 UTC, JHyeonC approved these changes
고생하셨습니다~

2024-09-03 06:09 UTC, wonjunYou approved these changes
고생하셨습니다~

2024-09-03 06:10 UTC, merged